// Central config for all onboarding engines.
// To add/change brokers, strategy codes, steps — edit here only.

export const engines = {
  commodities: {
    key: "commodities",
    label: "Commodities Strategy",
    algorithm: "ALGORITHM I",
    riskFactor: "Moderate-High",
    researchFocus: "Systematic identification of pricing inefficiencies across global commodity markets.",
    marketsCovered: "Global commodity futures including precious metals, energy, agricultural products, and macro-sensitive commodity markets.",
    strategyOverview: "Systematic commodity program focused on medium-to-long term trend persistence, macroeconomic dislocations, and quantitative execution across liquid global markets.",

    totalSteps: 5,
    steps: [
      {
        number: 1,
        type: "broker_account",
        title: "Open Your Broker Account",
        description: "Create your trading account through our approved brokerage partner.",
        brokerName: "VT Markets",
        brokerUrl: "https://vtm.pro/la1-com/en/v24Q9cYo",
        brokerInstructions: [
          "Open a VT Markets account using the link above.",
          "Complete identity verification.",
          "When creating your trading account select the settings below.",
        ],
        brokerSettings: [
          { label: "Platform", value: "MetaTrader 5 (MT5)" },
          { label: "Account Type", value: "RAW ECN" },
          { label: "Base Currency", value: "USD" },
        ],
        checkboxLabel: "My VT Markets account has been created",
        buttonLabel: "Continue",
      },
      {
        number: 2,
        type: "submit_details",
        title: "Submit Your Account Details",
        description: "We must verify that your account was opened through the correct referral process before granting strategy access.",
        fields: [
          { key: "detail_full_name", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
          { key: "detail_email", label: "Email Address", type: "email", placeholder: "your@email.com", required: true },
          { key: "detail_vt_user_id", label: "VT Markets User ID", type: "text", placeholder: "Your VT Markets user ID", required: true },
        ],
        checkboxLabel: "I confirm the information above is correct",
        buttonLabel: "Submit for Verification",
        pendingNote: "Pending Verification",
      },
      {
        number: 3,
        type: "fund_account",
        title: "Fund Your Trading Account",
        description: "Once your account has been verified, fund your VT Markets account.",
        fundingInstructions: [
          "Deposit funds into the MT5 RAW ECN USD account created in Step 2.",
        ],
        checkboxLabel: "My account has been funded",
        buttonLabel: "Continue",
      },
      {
        number: 4,
        type: "metacopier_account",
        title: "Create Your MetaCopier Account",
        description: "MetaCopier is used to connect your brokerage account to the north scale Commodities Engine.",
        platformName: "metacopier.io",
        platformUrl: "https://metacopier.io",
        metacopierInstructions: [
          "Create a MetaCopier account.",
          "Return here and submit the email address used for registration.",
          "north scale will use this email address to grant access to the Commodities Engine.",
        ],
        fields: [
          { key: "metacopier_email", label: "MetaCopier Email Address", type: "email", placeholder: "your@metacopier.io", required: true },
          { key: "metacopier_id", label: "MetaCopier Account ID", type: "text", placeholder: "Your MetaCopier account ID", required: true },
        ],
        checkboxLabel: "I have successfully created my MetaCopier account",
        buttonLabel: "Submit",
      },
      {
        number: 5,
        type: "metacopier_setup",
        title: "Configure MetaCopier",
        description: "Complete the MetaCopier setup process.",
        metacopierSetupInstructions: [
          { step: "Log into MetaCopier." },
          { step: "Navigate to: Dashboard → Payment Method" },
          { step: "Add a valid payment method using your personal details." },
          { step: "Navigate to: Projects → Add New Project" },
          { step: 'Create a project with the following name:', highlight: "ESXTrades - FX (AUD-NZD)" },
          { step: "Enter your project credentials." },
          { step: "Navigate to: Your Projects → Accounts" },
          { step: "Click the plus (+) button to add your VT Markets trading account." },
          { step: "Retrieve the following from your VT Markets account email: Server, Account Number, Password." },
          { step: "Use the funded trading account created in Step 2." },
        ],
        checkboxes: [
          { key: "cb_payment", label: "Payment method added" },
          { key: "cb_project", label: "Project created" },
          { key: "cb_broker", label: "Broker account connected" },
        ],
        buttonLabel: "Finish Setup",
      },
    ],
  },
  digital: {
    key: "digital",
    label: "Digital Assets Strategy",
    algorithm: "ALGORITHM II",
    riskFactor: "Aggressive",
    researchFocus: "Systematic allocation across digital asset markets using quantitative signals and volatility-aware risk management.",
    marketsCovered: "Major digital asset spot and derivatives markets featuring deep liquidity and institutional-grade execution venues.",
    strategyOverview: "Systematic digital asset program focused on liquid cryptocurrency markets, utilizing statistical arbitrage, quantitative signals, and disciplined risk management.",
    totalSteps: 5,
    steps: [
      {
        number: 1,
        type: "broker_account",
        title: "Open Your Broker Account",
        description: "Create your trading account through our approved brokerage partner.",
        brokerName: "VT Markets",
        brokerUrl: "https://vtm.pro/la1-com/en/v24Q9cYo",
        brokerInstructions: [
          "Open a VT Markets account using the link above.",
          "Complete identity verification.",
          "When creating your trading account select the settings below.",
        ],
        brokerSettings: [
          { label: "Platform", value: "MetaTrader 5 (MT5)" },
          { label: "Account Type", value: "RAW ECN" },
          { label: "Base Currency", value: "USD" },
        ],
        checkboxLabel: "My VT Markets account has been created",
        buttonLabel: "Continue",
      },
      {
        number: 2,
        type: "submit_details",
        title: "Submit Your Account Details",
        description: "We must verify that your account was opened through the correct referral process before granting strategy access.",
        fields: [
          { key: "detail_full_name", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
          { key: "detail_email", label: "Email Address", type: "email", placeholder: "your@email.com", required: true },
          { key: "detail_vt_user_id", label: "VT Markets User ID", type: "text", placeholder: "Your VT Markets user ID", required: true },
        ],
        checkboxLabel: "I confirm the information above is correct",
        buttonLabel: "Submit for Verification",
        pendingNote: "Pending Verification",
      },
      {
        number: 3,
        type: "fund_account",
        title: "Fund Your Trading Account",
        description: "Once your account has been verified, fund your VT Markets account.",
        fundingInstructions: [
          "Deposit funds into the MT5 RAW ECN USD account created in Step 2.",
        ],
        checkboxLabel: "My account has been funded",
        buttonLabel: "Continue",
      },
      {
        number: 4,
        type: "metacopier_account",
        title: "Create Your MetaCopier Account",
        description: "MetaCopier is used to connect your brokerage account to the north scale Digital Assets Engine.",
        platformName: "metacopier.io",
        platformUrl: "https://metacopier.io",
        metacopierInstructions: [
          "Create a MetaCopier account.",
          "Return here and submit the email address used for registration.",
          "north scale will use this email address to grant access to the Digital Assets Engine.",
        ],
        fields: [
          { key: "metacopier_email", label: "MetaCopier Email Address", type: "email", placeholder: "your@metacopier.io", required: true },
          { key: "metacopier_id", label: "MetaCopier Account ID", type: "text", placeholder: "Your MetaCopier account ID", required: true },
        ],
        checkboxLabel: "I have successfully created my MetaCopier account",
        buttonLabel: "Submit",
      },
      {
        number: 5,
        type: "metacopier_setup",
        title: "Configure MetaCopier",
        description: "Complete the MetaCopier setup process.",
        metacopierSetupInstructions: [
          { step: "Log into MetaCopier." },
          { step: "Navigate to: Dashboard → Payment Method" },
          { step: "Add a valid payment method using your personal details." },
          { step: "Navigate to: Projects → Add New Project" },
          { step: 'Create a project with the following name:', highlight: "ESXTrades - Digital Assets (BTC-USDT)" },
          { step: "Enter your project credentials." },
          { step: "Navigate to: Your Projects → Accounts" },
          { step: "Click the plus (+) button to add your VT Markets trading account." },
          { step: "Retrieve the following from your VT Markets account email: Server, Account Number, Password." },
          { step: "Use the funded trading account created in Step 2." },
        ],
        checkboxes: [
          { key: "cb_payment", label: "Payment method added" },
          { key: "cb_project", label: "Project created" },
          { key: "cb_broker", label: "Broker account connected" },
        ],
        buttonLabel: "Finish Setup",
      },
    ],
  },
  equities: {
    key: "equities",
    label: "Equity Indices Strategy",
    algorithm: "ALGORITHM III",
    riskFactor: "Moderate",
    researchFocus: "Systematic equity risk premia through data-driven factor allocation and disciplined portfolio construction.",
    marketsCovered: "Global equity index futures and sector-based equity exposures across developed and emerging markets.",
    strategyOverview: "Research phase. Future strategy development will focus on systematic equity allocation, portfolio diversification, and long-term risk-adjusted returns.",
    totalSteps: 5,
    steps: [
      {
        number: 1,
        type: "generic",
        title: "Create Your Copy Trading Account",
        description: "Create an account with our approved copy trading provider for the Equity Indices Engine.",
        providerName: "To be announced",
        providerUrl: "#",
        checkboxLabel: "I have created my copy trading account",
        buttonLabel: "Continue",
      },
      {
        number: 2,
        type: "generic",
        title: "Locate Strategy",
        description: "Search for the North Scale Equity Indices strategy using the code below.",
        strategyCode: "NS-EQ-001",
        searchInstructions: "Platform and search instructions will be provided upon broker announcement.",
        checkboxLabel: "I have located the strategy",
        buttonLabel: "Continue",
      },
      {
        number: 3,
        type: "generic",
        title: "Create Brokerage Account",
        description: "Create an account with the required brokerage platform for equity access.",
        brokerName: "To be announced",
        brokerUrl: "#",
        checkboxLabel: "My brokerage account is active",
        buttonLabel: "Continue",
      },
      {
        number: 4,
        type: "generic",
        title: "Fund Account",
        description: "Transfer funds to your brokerage account.",
        minimumAllocation: "To be announced",
        fundingInstructions: ["Funding instructions will be provided once the broker partnership is confirmed."],
        checkboxLabel: "My account has been funded",
        buttonLabel: "Continue",
      },
      {
        number: 5,
        type: "generic",
        title: "Connect and Activate",
        description: "Connect your brokerage account to the North Scale Equity Indices Engine.",
        connectionInstructions: "Connection instructions will be provided upon engine launch.",
        integrationGuide: "Integration guide will follow broker announcement.",
        checkboxLabel: "Connection completed — I am now copy trading",
        buttonLabel: "Finish Setup",
      },
    ],
  },
};

export const legalDisclaimer =
  "The information provided is for informational purposes only. Participation involves risk. Historical and illustrative research results do not represent actual investor returns. Past performance is not indicative of future results.";